package com.onedelhi.secure;

import android.os.Parcel;
import kotlin.Metadata;

@Metadata(bv = {}, d1 = {"\u0000&\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\b\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0005\n\u0002\u0010\u0011\n\u0002\b\u0003\bf\u0018\u0000*\u0004\b\u0000\u0010\u00012\u00020\u0002J#\u0010\b\u001a\u00020\u0007*\u00028\u00002\u0006\u0010\u0004\u001a\u00020\u00032\u0006\u0010\u0006\u001a\u00020\u0005H&¢\u0006\u0004\b\b\u0010\tJ\u0017\u0010\n\u001a\u00028\u00002\u0006\u0010\u0004\u001a\u00020\u0003H&¢\u0006\u0004\b\n\u0010\u000bJ\u001d\u0010\u000e\u001a\b\u0012\u0004\u0012\u00028\u00000\r2\u0006\u0010\f\u001a\u00020\u0005H\u0016¢\u0006\u0004\b\u000e\u0010\u000f¨\u0006\u0010"}, d2 = {"Lcom/onedelhi/secure/vy2;", "T", "", "Landroid/os/Parcel;", "parcel", "", "flags", "Lcom/onedelhi/secure/un4;", "a", "(Ljava/lang/Object;Landroid/os/Parcel;I)V", "b", "(Landroid/os/Parcel;)Ljava/lang/Object;", "size", "", "newArray", "(I)[Ljava/lang/Object;", "parcelize-runtime"}, k = 1, mv = {1, 5, 1})
public interface vy2<T> {

    @ii2(mo38106k = 3, mo38107mv = {1, 5, 1}, mo38109xi = 48)
    /* renamed from: com.onedelhi.secure.vy2$a */
    public static final class C7112a {
        @vr2
        /* renamed from: a */
        public static <T> T[] m68636a(@vr2 vy2<T> vy2, int i) {
            jt1.m53777p(vy2, "this");
            throw new ur2("Generated by Android Extensions automatically");
        }
    }

    /* renamed from: a */
    void mo46446a(T t, @vr2 Parcel parcel, int i);

    /* renamed from: b */
    T mo46447b(@vr2 Parcel parcel);

    @vr2
    T[] newArray(int i);
}
